#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     proto,          sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     HTSMUX,              sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightRotate,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevatorRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightDrive2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftRotate,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     elevatorLeft,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftDrive2,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "autonoLib.c"

task main()
{
	writeValueToLEDs(0);
	autonomousOptimized = true;
	initSwerve();
	initLift();
	lineFollowerInit();
	writeValueToLEDs(IDLE);
	waitForStart();
		initGyro();

	setModulePositions(1440);

	resetDistance();
	while ( !driveToCenter(false) )
	{
		updateGyro();
		updateSwerve();
		updateLift();
	}
}
