\#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     proto,          sensorI2CCustom9V)
#pragma config(Sensor, S3,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     rightRotate,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     elevatorRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightDrive2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     leftRotate,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     elevatorLeft,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     leftDrive2,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nNxtButtonTask = -2;
	while ( true )
	{
		nxtDisplayString(0, "%i", nMotorEncoder[elevatorLeft]);
		switch (nNxtButtonPressed)
		{
			case kLeftButton:
				motor[elevatorRight] = -100;
				motor[elevatorLeft] = 100;
				break;
			case kRightButton:
				motor[elevatorRight] = 100;
				motor[elevatorLeft] = -100;
				break;
			default:
				motor[elevatorRight] = 0;
				motor[elevatorLeft] = 0;
			break;
		}
	}

}
